spring:
  application:
    name: ams
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ams?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.187.130
    port: 6379
    password: 123456
    pool:
      max-active: 20
      max-wait: 20
      max-idle: 10
      min-idle: 0
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.four.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl